### ISSUE TITLE
Remove all 'translate' logic from run_tests.sh

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#118]
The host:translate parameter defaults to false, as it should.  It ought to be overridable on either the command line or in a config file, but config file override doesn't work because it is special-cased in run_tests.sh.  I'm pretty sure that simply removing these three lines should make it all work, but I suppose this belief ought to be tested.

```
if [[ ! "$config_specs" =~ "host:allowwrite=" ]]; then
    config_specs="$first_config_spec $* host:allowwrite=false"
fi
```

**Comment by mtholder** [comment]
these lines require the that the `allowwrite` option be specified by the command line (rather than conf file). I, personally, do not care if that behavior is retained or not.

But I'm not sure how this interacts with `host:translate` Is there some interaction between `host:allowwrite` and `host:translate`? If so, is that documented?

**Comment by jar398** [comment]
I think this has been fixed. In any case, there is no longer any special treatment of host:translation in run_tests.sh in this repo, so I will close.
