### ISSUE TITLE
Need to remove ott_ids_not_in_tree results from spec

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#52]
Although tm-lite loads the taxonomy, it throws away the information that would be needed to implement this part of the spec, and keeping it would be an unacceptable implementation burden. So it seems we need to have the service respond with 400s when the client provides valid OTT ids that are not in the tree, and change the spec document.

This is an incompatible change from v2.

I have no idea whether any users are depending on this (or the `invalid_nodes` feature, which was also removed, for different reasons). An option is to provide an alternative: one tree_of_life method that takes a list of node ids and checks them for validity (replacing the former invalid_nodes feature), and a second taxonomy method that takes a list of taxon ids and checks them for validity (replacing the ott_ids_not_in_tree feature).

**Comment by mtholder** [comment]
I don't object to omitting this from this version of the API.

Just a note to say: the newest version of the synthesis pipeline will also produce a JSON that describes the MRCA and attachment points for all of the OTT Ids that are:
  1. not filtered (because of flags), but
  2. were not placed in the tree, because phylogenetic inputs rendered them non-monophyletic.

So, when we get that feature documented, we may want to add a richer return value (richer than a list of `ott_ids_not_in_tree`) that describes why the OTT ids were omitted.

It should be possible to indicate what flags were the cause of a taxon being pruned as well.

This could be done as a simple adaptor that holds this information in memory and
  1. delegates a call to tm-lite,
  2. fills in these "reasons for absence" details in the event of a 400

**Comment by kcranston** [comment]
I am also ok with removing `ott_ids_not_int_tree` for this version, with the plan for a (hopefully compatible) change in the next version that provides the richer information that @mtholder describes.

**Comment by josephwb** [comment]
That sounds good to me.

**Comment by jar398** [comment]
I wonder if we should ask our API users if any of them are using the feature?
