### ISSUE TITLE
provide arguson through tree_of_life/subtree service

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/germinator#53]
The [current version of the spec](https://docs.google.com/document/d/1XcgoQGJVxSgk-yKB-NAayQNZ2_QUQuw9_RIvbR2LeTw/edit#heading=h.ko91c769kjpv) proposes that the subtree service returns arguson when format=arguson (the other option is format=newick). It also proposes  changes to the arguson format, largely for consistency with other methods. The current API returns arguson through the (unpublicized) [treemachine/getSyntheticTree](https://docs.google.com/document/d/1HTDZijGVWCT2ZKbalRMXvYeiPmYDralyMzFRQHuqsTc/edit#heading=h.rr79sb298qna).

There are a couple of (non-independent) questions to address:
* should we include arguson in the public API?
* should we change the [current arguson format](https://docs.google.com/document/d/1HTDZijGVWCT2ZKbalRMXvYeiPmYDralyMzFRQHuqsTc/edit#heading=h.smk69mu0p5i)?
* should arguson be returned as part of subtree, or in a separate method?

It would be helpful to know from @josephwb what changes are required to tmlite to implement the V3 spec as written.

**Comment by jar398** [comment]
We cannot use the current arguson format because it has integer node ids in it.

**Comment by josephwb** [comment]
No it doesn't; it has the same node_ids as everything else.

**Comment by jar398** [comment]
The current arguson format, as documented in the document Karen linked to, and as implemented in the production treemachine and tree browser, says that node ids are integers. So we can't use it as it stands.

We could consider variations on it, such as a format that's the same except for having string node ids.

**Comment by josephwb** [comment]
To be clear: @jimallman and I worked on updating the arguson to be compatible with the new graph and annotations (i.e. changes made in both treemachine and browser) quite a while ago.

The issue here is that arguson is produced from a separate (idiosyncratic) class. I can move it over to the other code (obviously desirable), but it would require a rewrite. So, this is more than a cosmetic change. I can do it, but it seems low priority given that 1) it works as it is (from GoLS) and 2) only the browser _currently_ uses arguson (although @mtholder tells me others in Arbor have expressed interest).

My inclination is to save this change for version 4.

**Comment by kcranston** [comment]
We've made this decision and `subtree` is now returning arguson. Yay!
